# Generated by Django 2.2.12 on 2020-07-02 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200604_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='text',
        ),
        migrations.AddField(
            model_name='work',
            name='address',
            field=models.CharField(default='test', max_length=200, verbose_name='現場住所'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='work',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='作業内容'),
        ),
        migrations.AddField(
            model_name='work',
            name='staff',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='現場担当者'),
        ),
        migrations.AddField(
            model_name='work',
            name='tel',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='電話番号'),
        ),
        migrations.AlterField(
            model_name='work',
            name='title',
            field=models.CharField(max_length=200, verbose_name='タイトル'),
        ),
    ]
