# Generated by Django 2.2.12 on 2020-07-07 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200702_2015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='content',
            new_name='text',
        ),
    ]
