# Generated by Django 2.2.12 on 2020-07-27 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_post_published_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
