# Generated by Django 2.2.12 on 2020-08-13 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200801_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='app.Category', verbose_name='カテゴリ'),
            preserve_default=False,
        ),
    ]
