# Generated by Django 2.2.12 on 2020-08-17 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_post_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='カテゴリ')),
            ],
        ),
        migrations.RenameModel(
            old_name='Category',
            new_name='PostCategory',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='category',
            new_name='post_category',
        ),
        migrations.RemoveField(
            model_name='work',
            name='category',
        ),
        migrations.AddField(
            model_name='work',
            name='work_category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='app.WorkCategory', verbose_name='カテゴリ'),
            preserve_default=False,
        ),
    ]
