# Generated by Django 2.2.18 on 2021-02-07 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20210207_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='price',
            field=models.CharField(default=1, max_length=50, verbose_name='料金'),
            preserve_default=False,
        ),
    ]
